theme: jekyll-theme-minimal
title: Desmond Vehar
description: |
  I'm an experienced Software Engineer that loves making an impact and helping others.
  I've had a breadth of experiences including Backend and Frontend development, and enjoy working with new technologies. I also have a passion for and a proven track record of shaping company culture and developing more equitable hiring practices.

  Feel free to reach out!
show_downloads: true
linkedin_url: https://www.linkedin.com/in/desmond-vehar/
resume_url: https://dvehar.github.io/files/Desmond_Vehar_Resume.pdf
